# Generated by Django 4.0.2 on 2022-02-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('country', models.CharField(default='Iran', help_text='Please Enter your country(default: Iran).', max_length=30, verbose_name='country')),
                ('province', models.CharField(help_text='Please Enter your province(Tehran, Shiraz, ...)', max_length=30, verbose_name='province')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('detail', models.CharField(help_text='Please Enter details of yout address(like street, allay and so on...)', max_length=255, verbose_name='address')),
                ('postal_code', models.CharField(help_text='Please Enter your zip code', max_length=10, unique=True, verbose_name='Zip code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
