# Generated by Django 4.0.2 on 2022-02-21 01:19

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Please Enter your first name', max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Please Enter your last name', max_length=30, verbose_name='Last Name')),
                ('username', models.CharField(help_text='Please Enter your username', max_length=30, unique=True, verbose_name='Username')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('country_en', models.CharField(default='Iran', help_text='Please Enter your country in English(default: Iran).', max_length=30, verbose_name='country in english')),
                ('country_fa', models.CharField(default='Iran', help_text='Please Enter your country in Persian(default: Iran).', max_length=30, verbose_name='country in persian')),
                ('province_en', models.CharField(help_text='Please Enter your province in English(Tehran, Shiraz, ...)', max_length=30, verbose_name='province in english')),
                ('province_fa', models.CharField(help_text='Please Enter your province in Persian(Tehran, Shiraz, ...)', max_length=30, verbose_name='province in persian')),
                ('city_en', models.CharField(help_text='Please Enter your city in English', max_length=30, verbose_name='city in english')),
                ('city_fa', models.CharField(help_text='Please Enter your city in Persian', max_length=30, verbose_name='city in persian')),
                ('detail_en', models.CharField(help_text='Please Enter details of yout address in English(like street, allay and so on...)', max_length=255, verbose_name='address in english')),
                ('detail_fa', models.CharField(help_text='Please Enter details of yout address in Persian(like street, allay and so on...)', max_length=255, verbose_name='address in persian')),
                ('postal_code', models.CharField(help_text='Please Enter your zip code', max_length=10, unique=True, validators=[core.validators.Validators.check_postal_code], verbose_name='Zip code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
