# Generated by Django 4.0.2 on 2022-02-21 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total price')),
                ('final_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Final proce')),
                ('status', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid'), ('C', 'Canceled')], default='U', max_length=1, verbose_name='Order Status')),
                ('address', models.ForeignKey(help_text='Please select your address', on_delete=django.db.models.deletion.RESTRICT, to='customer.address', verbose_name='Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer', verbose_name='customer cart')),
                ('off_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.offcode')),
            ],
            options={
                'unique_together': {('off_code', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('count', models.PositiveIntegerField(default=1, help_text='How many Items would you like to order?', validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of Order Items')),
                ('order', models.ForeignKey(help_text='Please select your order', on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='order.order', verbose_name='Receipt')),
                ('product', models.ForeignKey(help_text='Please select Product Item to add', on_delete=django.db.models.deletion.RESTRICT, to='product.product', verbose_name='Product name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
