# Generated by Django 4.0.2 on 2022-02-21 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('name_en', models.CharField(help_text='Please Enter category name in English', max_length=30, verbose_name='Category in english')),
                ('name_fa', models.CharField(help_text='Please Enter category name in Persian', max_length=30, verbose_name='Category in persian')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('value', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('price', 'Price'), ('percent', 'Percent')], max_length=10)),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('value', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('price', 'Price'), ('percent', 'Percent')], max_length=10)),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(help_text='What is this discount for?', max_length=30, verbose_name='Disscount title')),
                ('code', models.CharField(help_text='Please Enter Off code', max_length=10, unique=True, verbose_name='Discount code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('name_en', models.CharField(help_text='Please Enter product name in english', max_length=30, verbose_name='Product name in english')),
                ('name_fa', models.CharField(help_text='Please Enter product name in persian', max_length=30, verbose_name='Product name in persian')),
                ('brand_en', models.CharField(help_text='Please Enter brand name in english', max_length=30, verbose_name='Brand name in english')),
                ('brand_fa', models.CharField(help_text='Please Enter brand name in persian', max_length=30, verbose_name='Brand name in persian')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(null=True, upload_to='../static/images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
